FROM python:3.13.3-alpine

WORKDIR /my-app/py-api
COPY requirements.txt .

RUN pip3 install --no-cache-dir -r requirements.txt

EXPOSE 3401

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "3401", "--reload"]